### ISSUE TITLE
Transparancy in static images when converting telegram to signal

### ISSUE THREAD

**Issue by Duckbilled** [laggykiller/sticker-convert#1]
I have issues converting Telegram to Signal packages when there are static images in the pack like https://t.me/addstickers/FluentEmoji8

Is there anyway to solve this?

**Comment by laggykiller** [comment]
Thank you for your report. Can confirm that webm static images lost transparency after conversion.

webm static images were processed by ImageMagick, which failed to handle transparency.

Using ffmpeg to process webm static images with vp9 codec solved the problem.

1.5.16 should solve this problem, please check: https://github.com/laggykiller/sticker-convert/releases
