### ISSUE TITLE
Wrong timing when converting from WEBM to APNG

### ISSUE THREAD

**Issue by sindastra** [laggykiller/sticker-convert#114]
Sometimes, converting from WEBM to APNG (e.g. Telegram to Signal) the timing of the resulting APNG is wrong. Here's an example:

[026.webm](https://github.com/laggykiller/sticker-convert/assets/1236984/2e810f36-4829-44e8-a2b4-5191b9086ec4)

![026](https://github.com/laggykiller/sticker-convert/assets/1236984/81a0d81e-7144-46eb-9ec2-9feb176b22f7)

You can download the original files here to try to reproduce: [comparison.zip](https://github.com/laggykiller/sticker-convert/files/14100994/comparison.zip)

**Comment by laggykiller** [comment]
Your webm file is a bit special, it seems like pyav had trouble in reading in all frames of the webm file. On macOS arm64, only 23 frames out of 152 frames were read. On Windows and Arch Linux, it even crashes sticker-convert.

As not all frames are read, it gives the illusion of sped up video

I am reporting to pyav: https://github.com/PyAV-Org/PyAV/issues/1269

**Comment by laggykiller** [comment]
Turns out the fps we get from metadata of pyav is not reliable, so we need to calculate it by ourselves.

For the crash, the webm file is yuva420p, and pyav is not handling it well. This should fix it: https://github.com/laggykiller/sticker-convert/commit/cc568d9f0c37b3092388dd64eade81d57310726e

Should be fixed in v2.3.0, please check!

**Comment by sindastra** [comment]
As we can see here, the APNG has correct timing now:

![026 fixed](https://github.com/laggykiller/sticker-convert/assets/1236984/281c470c-0298-4d18-a05b-7f48b0f4a5b5)

But I wonder, is it just me, or are the colors wrong/too saturated in this result?

**Comment by laggykiller** [comment]
The conversion of YUV to RGB was incorrect

This should fix it https://github.com/laggykiller/sticker-convert/commit/b6921c60562556b61c867f1279e884c5dba750cd

**Comment by laggykiller** [comment]
Should be fixed in v2.3.1

https://github.com/laggykiller/sticker-convert/releases

**Comment by sindastra** [comment]
Yes, this looks better now:

![026 fixed](https://github.com/laggykiller/sticker-convert/assets/1236984/7844be8a-d084-46b7-bd54-4026b9078307)
