### ISSUE TITLE
[request] support for Telegram emoji

### ISSUE THREAD

**Issue by sideloading** [laggykiller/sticker-convert#115]
Can this program support downloading Telegram emoji?

Example URLs
https://t.me/addemoji/ragemojis
https://t.me/addemoji/yipasheemoji
https://t.me/addemoji/CatsBigPack

**Comment by laggykiller** [comment]
Added support, please try v2.5.3

https://github.com/laggykiller/sticker-convert/releases

**Comment by sideloading** [comment]
@laggykiller thanks for the quick update, it downloads.

is there any chance of keeping the original transparency? for example the https://t.me/addemoji/CatsBigPack has a few emojis that have solid black/white background instead of being transparent

**Comment by laggykiller** [comment]
Stickers in sticker_input are downloaded directly from source without modifications. I can confirm that the pack you mentioned contains some sticker with transparent background, and the files downloaded do have transparent background.

If there is no bugs, stickers in sticker_output should also have transparent background.

Can you upload the files that do not have transparent background? What is the compression setting?

**Comment by laggykiller** [comment]
btw you can check with tools like https://rotato.app/tools/transparent-video

**Comment by laggykiller** [comment]
I am closing it for now. Please also try v2.6.0
