### ISSUE TITLE
Issue with .tgs to .gif Conversion Resulting in Black Output

### ISSUE THREAD

**Issue by xwxYa** [laggykiller/sticker-convert#134]
I'm reaching out to report a problem I encountered while using the sticker-convert tool. I attempted to convert a .tgs file to a .gif format, expecting a proper animated sticker as a result. However, the output is a completely black image, which doesn't reflect the original .tgs content.

Steps to Reproduce:
  I selected the .tgs file as input using the GUI.
  I set the conversion options with the intention of converting to .gif format
  The conversion process completed without error messages, but the resulting .gif is entirely black.

Expected Result:
  A .gif file that accurately represents the animated content of the .tgs file.
![1](https://github.com/laggykiller/sticker-convert/assets/137683458/2ee894bc-ff7c-43ca-b57b-dc99b30681c3)

Actual Result:
  The output .gif file is entirely black with no visible content or animation.
![2](https://github.com/laggykiller/sticker-convert/assets/137683458/b2e6b535-e871-4b9a-8a9e-d1b10ae00b36)

Attempted Resolutions:
  Verified that the .tgs file displays correctly in Telegram.
  Ensured that I'm using the latest version of sticker-convert.

Additional Information:
  Version of sticker-convert used: [Release v2.7.7]
  Operating System: Windows 11

  I can provide the original .tgs file and the resulting .gif for your review if needed.
  I appreciate any assistance you can provide and am happy to supply any further information required to diagnose and resolve this issue. Thank you for your time and for maintaining this helpful tool😭😭😭

Best regards

**Comment by xwxYa** [comment]
Strange, why are the files under "Actual Result:" in white?🤔
I swear what I saw on my computer was black! 
![image](https://github.com/laggykiller/sticker-convert/assets/137683458/a2abbf87-ed8f-42a7-b7a3-507b7517b81a)

**Comment by laggykiller** [comment]
Your gif has transparent background with black drawings on it. For some reason pyav converts all pixels to transparent. On your computer is all black because the OS renders image thumbnail that has all transparent pixels as all black.

v2.7.8 create gif with Pillow instead of pyav, which should solve this problem. Please try.

**Comment by xwxYa** [comment]
I’ve successfully used the latest version of sticker-convert to transform .tgs files into GIF!
However, the output GIFs have a white background. I'd like to set this background to be transparent. Could you guide me on how to achieve this within the tool, if possible🥺

**Comment by laggykiller** [comment]
The background should be transparent from my testing... How do you come to conclusion that it is not transparent?

**Comment by xwxYa** [comment]
Thank you for suggesting the online GIF analysis tool! After checking, it shows that the transparency index is 0 (not used), confirming the background should indeed be transparent. But typically when I convert .tgs to .gif, the output is transparent, which puzzles me as to why it didn't work this time😢

**Comment by laggykiller** [comment]
ok, something is off here. What is the version of sticker-convert? What are the settings of sticker-convert? Also show the advanced compression settings if you changed anything.

**Comment by xwxYa** [comment]
I'm using the latest version, v2.7.10. The settings are as shown in the attached screenshots, and I haven't made any changes to the advanced compression settings beyond the default. Attached is one of the [.tgs files](https://pixeldrain.com/u/CZQL8sTV) I'm trying to convert.
<img width="947" alt="04eb4a5ae2ef53ef889fff015a03a1e" src="https://github.com/laggykiller/sticker-convert/assets/137683458/485fd587-3403-4c63-947b-e3e1e9725f7e">

Thanks again for looking into this.

**Comment by laggykiller** [comment]
GIF supports transparency with a catch. It only supports one color to become the transparent color. Converting the gif you gave in the first comment produce GIF with transparency successfully as it only contain one transparent color. Converting the tgs file produce gif without transparency as it contained multiple transparent colors and Pillow was confused when exporting the gif.

Anyway, gif export goes through alpha quantization first so that there is only one transparent color. v2.7.11 should fix this, please try.

**Comment by xwxYa** [comment]
Apologies for the oversight QAQ; I am using a Windows system. Do you have plans to release a Windows-compatible version of the update (v2.7.11) in the near future?

**Comment by laggykiller** [comment]
Windows version was building in github action. You can download now.

**Comment by xwxYa** [comment]
I wanted to let you know that the issue has been perfectly resolved with the updated Windows version of sticker-convert v2.7.11. I truly appreciate your prompt support and the work you've put into this tool! Thank you very much!
![12](https://github.com/laggykiller/sticker-convert/assets/137683458/9f4dd95d-90a1-4cf7-95c1-126ee11bedec)
