### ISSUE TITLE
Pillow issue

### ISSUE THREAD

**Issue by NicolasPL64** [laggykiller/sticker-convert#151]
When converting from TG to WA or just saving/loading it locally, and setting the min FPS to 60, I get stuck in this message.

![image](https://github.com/laggykiller/sticker-convert/assets/31411531/eaa0d809-0124-441d-9003-bd8c4e22d329)

I tried converting a TG sticker pack to WA with the WhatsApp preset but I get really low FPS in the result (around 20fps).
Any fix for this?

**Comment by laggykiller** [comment]
This is only a warning, it should convert successfully if you wait patiently.

Are there any messages in terminal (black window) that you did not capture?

**Comment by laggykiller** [comment]
Closing as this is not bug and there is no reply.
