### ISSUE TITLE
Could not download animated stickers on kakaotalk

### ISSUE THREAD

**Issue by takyeon2** [laggykiller/sticker-convert#171]
Got auth token on GUI but still could not get the animated stickers. T.T

**Comment by laggykiller** [comment]
Tested just now, no problem.

Please read guide: https://github.com/laggykiller/sticker-convert/blob/master/docs/guide_kakao.md

Please also note that using share link method is recommended.

**Comment by laggykiller** [comment]
Likely not bug and no reply. Closing.

**Comment by vyeol** [comment]
I'm experiencing issues with downloading animated stickers as well.

I am using the share link method as described and recommended in the docs, i.e. got the link from with the store in the app, and made sure to check that the link format is correct.

However, when starting the download, the progress output is showing an AssertionError.

This happens with links to static icon packs as well.

Download of the static versions of animated stickers using the link format from the web browser store is working for me.

**Comment by laggykiller** [comment]
Fixed in 2.9.2

**Comment by laggykiller** [comment]
Try 2.9.3, it no longer depends on chrome for downloading kakao stickers using share link

**Comment by vyeol** [comment]
Tried with 2.9.3, now ultimately getting the following:

```
##########
Summary:
##########

Export result: None
```

Neither animated nor static stickers with share link method are downloading, input source is set to either auto detect or to download from Kakao, output options are set to save to local directory only.

**Comment by laggykiller** [comment]
@vyeol Check inside `stickers_input` directory? Should be inside.

There should be more messages above summary, please send.

Are you using macOS for testing?

**Comment by vyeol** [comment]
I know you're on the case already, but just to confirm:

The `stickers_input` directory is empty, and yes, using macOS for testing.

Looking forward to your findings for the compiled version.

**Comment by laggykiller** [comment]
@vyeol Let's follow up the issue here: https://github.com/laggykiller/sticker-convert/issues/186

**Comment by laggykiller** [comment]
@vyeol Your issue should be solved in v2.9.4

**Comment by vyeol** [comment]
Error on app version 2.10.18, macOS 15.1.1:

av.error.InvalidDataError: [Errno 1094995529] Invalid data found when processing input: '/Users/USER/Downloads/sticker-convert-macos-arm64/output/.DS_Store'
#####################
An error occured while exporting stickers
An error occured during this run.
