### ISSUE TITLE
"No Compression" Option Results in Incorrect Pack Uploads

### ISSUE THREAD

**Issue by RABIDYOTE** [laggykiller/sticker-convert#190]
When I'm converting stickers and specifically have the option "No compression" toggled, the program will take whatever images were previously dropped into the `sticker_output` folder and use those instead of the intended ones. This resulted in me uploading multiple duplicate packs to Signal with the wrong metadata and caused a bit of frustration until I figured out why it was happening.

To prevent this from happening, I believe there should be an option to clear the folder of any files before starting to download any packs, or to stop the converter from grabbing files if there are none outputted in the first place.

**Comment by laggykiller** [comment]
Not clearing `stickers_output` if "no compression" is on is a feature, not a bug. This is for users who want to upload local files to messaging apps directly that does not require compression (e.g. after edit "emoji.json")
