### ISSUE TITLE
Xcode project file fails to open due to (likely) app icons being exported in the wrong size

### ISSUE THREAD

**Issue by jdblackiii** [laggykiller/sticker-convert#197]
Issue is on 2022 M2 Mac Air, using GUI version downloaded from pip.

![image](https://github.com/user-attachments/assets/9bf10f1a-c72a-439a-a974-0958bb2e6cc1)
Manually dragging the generated app icons into a new project reveals the issue.

![image](https://github.com/user-attachments/assets/eb152542-2e9d-4ac0-99cb-0d36fb2725bb)
The iPhone 29x29 3x, 60x45 3x and 27x30 3x are all one pixel off. I would venture to guess somewhere you're converting between an int and a float.

**Comment by laggykiller** [comment]
I know what is going on. Some video formats does not like to be resized to odd numbered dimensions, so I just round up to an even number.

I will fix this...

**Comment by laggykiller** [comment]
Fixed in v2.10.3
