### ISSUE TITLE
Line Pop up stickers

### ISSUE THREAD

**Issue by extremelyonline** [laggykiller/sticker-convert#21]
Hi, it seems that Line Pop up stickers cannot be converted to Signal animated stickers. Is that a way/ a preset that can make it work? Thanks!

**Comment by laggykiller** [comment]
I only considered downloading Line animated and static stickers, not other stickers such as pop up stickers.

v1.15.0 would allow downloading all the other types of Line stickers, including pop up stickers. Have a try.

**Comment by laggykiller** [comment]
Closing for now, please reopen if there is issue.
