### ISSUE TITLE
image ratio when compressing

### ISSUE THREAD

**Issue by gunnerguaren** [laggykiller/sticker-convert#223]
upload做signal sticker時因file size要compress
請問有得set保持圖檔比例而唔係強制正方形嗎?

**Comment by laggykiller** [comment]
https://support.signal.org/hc/en-us/articles/360031836512-Stickers#:~:text=Each%20sticker%20must%20be%20imported,with%20a%2016%20px%20margin.

Signal stickers must be 512x512.

However, sticker-convert would auto pad transparent pixels to image to meet size requirement and still have same aspect ratio visually.

**Comment by gunnerguaren** [comment]
但剛才再嘗試upload上去都依然crop走哂
因github唔support apng檔所以我放入zip
webm係原檔, apng係compressed file
preset揀auto同signal都試過都一樣crop走右邊
[01.zip](https://github.com/user-attachments/files/17956928/01.zip)
![image](https://github.com/user-attachments/assets/af9d3e30-9aab-4d0b-b543-9188cfad3433)

**Comment by laggykiller** [comment]
Thanks for reporting, fixed in v2.10.7
