### ISSUE TITLE
Can't upload to telegram

### ISSUE THREAD

**Issue by rodtang1973** [laggykiller/sticker-convert#230]
Creating pack and bulk uploading 118 stickers with same format of_by_Uploader_stickerMyownbot
Cannot create pack and bulk upload 118 stickers with same format of Uploader_stickerMyownbot due to Request Entity Too Large (413)
An error occured while exporting stickers
An error occured during this

**Comment by laggykiller** [comment]
What format are those stickers in? What is the total size of all stickers inside "stickers_output" folder?

**Comment by laggykiller** [comment]
can you zip and share both stickers_input and stickers_output?

**Comment by laggykiller** [comment]
Thanks for reporting, fixed in v2.10.9
