### ISSUE TITLE
Can't click on the "Start" button

### ISSUE THREAD

**Issue by azuredusk10** [laggykiller/sticker-convert#3]
Hi, thank you for spending the time making this app. My partner and I love sending animated stickers on Signal and I'm excited to try this out.

Unfortunately I couldn't reach the start button on Mac OS for two reasons:
1) I couldn't scroll down to reach anything which is off-screen. Unfortunately my 15" Macbook laptop screen wasn't tall enough to show everything in one go

<img width="698" alt="Screenshot 2022-12-28 at 20 43 09" src="https://user-images.githubusercontent.com/18142893/209869994-4aa2d068-194f-4439-b895-4fb4ff96f6c8.png">

2) I reduced the display scaling so I could make the window taller, but even at the window's maximum height,  the start button is too short and too close to the window edge. As a result, when I try to click on it, Mac OS thinks I'm trying to resize the window instead.

<img width="877" alt="Screenshot 2022-12-28 at 20 49 16" src="https://user-images.githubusercontent.com/18142893/209870477-313e43b6-eac2-4771-81ac-a36f37fb63a0.png">

I'm running the program on Mac OS 12.4 , on a Mid-2015 15" Macbook Pro.

Thanks

**Comment by azuredusk10** [comment]
When I reopened the app with my laptop's display scaling already reduced, the "Start" button enough was tall enough to click on.

**Comment by laggykiller** [comment]
Thank you for reporting the bug. I shall fix this when I have more free time (~1 week later?)

**Comment by laggykiller** [comment]
I have redesigned the GUI such that the dimension can fit in most screen

Check v1.6.2

I might make the whole window scrollable in the future

**Comment by azuredusk10** [comment]
All the UI elements now fit easily on the default Mac OS scaling setting for a 15" laptop screen. Thank you for changing this so quickly! This solves the issue for me.

Screenshot of how much space the app takes on my laptop screen with scaling set to "Default":
<img width="1440" alt="Screenshot 2022-12-29 at 21 44 40" src="https://user-images.githubusercontent.com/18142893/210013887-ddad0491-968f-428f-9842-3510070c62be.png">
