### ISSUE TITLE
AppImage is open to MITM attacks

### ISSUE THREAD

**Issue by hwittenborn** [laggykiller/sticker-convert#39]
Sorry if this isn't the best place to post this, I couldn't find any other place to send this. Feel free to close/delete this and contact me via any other means if you feel it'd be more appropriate.

The [AppImage build file](https://github.com/laggykiller/sticker-convert/blob/master/AppImageBuilder.yml) doesn't authenticate APT sources, while also using the HTTP versions of the Ubuntu repositories. This makes downloads from the repository open to MITM attacks, which could lead to infected packages being present in the built AppImage.

You should add Ubuntu's GPG key URL to at least one of the `archive.ubuntu.com` sources and all of the PPA sources, and then you should be able to remove the `allow_unauthenticated` line just fine.

**Comment by laggykiller** [comment]
Did not add it as I am too lazy to do so and don't think someone would MITM attack a github-hosted runner.

Anyway, added GPG key URLs and remove `allow_unathenticated` in v1.17.0

**Comment by hwittenborn** [comment]
That's fair that people probably wouldn't attack a GitHub Actions runner, but I don't think it ever hurts to make it all more secure, especially when on the off-chance someone did do a MITM attack against a runner it would be fairly impossible to notice. I appreciate you getting that all fixed though, thanks a ton!
