### ISSUE TITLE
Swiftkey support 

### ISSUE THREAD

**Issue by HyperCriSiS** [laggykiller/sticker-convert#68]
Hi,

Can you maybe add support for swiftkey?
That would be really awesome.
Would be convenient to have all stickers in one place available everywhere.

Regards
Hyper

**Comment by laggykiller** [comment]
In what way do you want me to support stickers in keyboard applications such as swiftkey and Gboard? It is already easy to create own sticker pack within the application (just press create and select file)

Do those applications require specific image resolution, size, format? I cannot find any reference about this...

**Comment by laggykiller** [comment]
Closing this for now
