### ISSUE TITLE
Pressing "Choose directory" doesn't open the file browser

### ISSUE THREAD

**Issue by azuredusk10** [laggykiller/sticker-convert#9]
On version v1.9.6 on Mac OS, when clicking "Choose directory..." in the GUI, nothing happens, and an error is logged in the terminal.

To reproduce:
1. Set "Input source" to "From local directory"
2. Next to "Input directory", press "Choose directory..."

Expected result:
File browser opens and allows me to navigate to the input folder and select it.

Actual result:
This error is shown in the terminal.
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter/__init__.py", line 1948, in __call__
  File "gui.py", line 329, in callback_set_indir
AttributeError: 'InputFrame' object has no attribute 'input_setdir_var'
```

**Comment by laggykiller** [comment]
Thank you for your report. Fixed with v1.9.7
