### ISSUE TITLE
Help about limit of sticker on .wasticker files

### ISSUE THREAD

**Issue by AlanTol** [laggykiller/sticker-convert#99]
I was looking to create .wasticker files with more than 30 stickers on it, and I found this proyect but it also that limit of sticker per file. There is any way to modify the code to increse the number of sticker in the .wastickers files?

**Comment by laggykiller** [comment]
See https://github.com/WhatsApp/stickers/issues/107#issuecomment-434845340

The 30 stickers limit is imposed by WhatsApp, not me. wastickers file with >30 stickers are invalid and cannot be imported to WhatsApp.

To overcome, sticker-convert automatically splice stickers into packs with <=30 stickers.
